version: 2

models:
  - name: int_curated_sanctions_entities
    columns:
      - name: sanctions_entity_id
        tests: [not_null, unique]
      - name: primary_name_normalized
        tests: [not_null]
  - name: int_curated_funds
    columns:
      - name: fund_id
        tests: [not_null, unique]
  - name: int_curated_holdings
    columns:
      - name: holding_id
        tests: [not_null, unique]
      - name: issuer_name_normalized
        tests: [not_null]

